# https://dart.dev/guides/language/analysis-options
analyzer:
  # Врубаем построже типизацию
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  # Игнорим кодогенерацию
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"

# Врубаем линтер
# https://dart.dev/guides/language/analysis-options#effective-dart-rules
include: package:effective_dart/analysis_options.yaml


linter:
  rules:
    directives_ordering: false
    prefer_relative_imports: false
    avoid_catching_errors: false
    prefer_function_declarations_over_variables: false